remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Ruiwei Xiao
logo:

description: >
  2nd Year PhD Student at CMU HCII  
  <br/><br/>

  <p style="line-height: 1.8;">

    <a href="https://scholar.google.com/citations?user=izYxC3EAAAAJ&hl=en" target="_blank" style="text-decoration:none;">
      <img src="https://img.icons8.com/ios-filled/26/4a90e2/school.png" style="vertical-align:middle;"/> 
      &nbsp;Google Scholar
    </a>
    <br/>

    <a href="https://github.com/ruiweix" target="_blank" style="text-decoration:none;">
      <img src="https://img.icons8.com/ios-glyphs/26/4a90e2/github.png" style="vertical-align:middle;"/> 
      &nbsp;Github
    </a>
    <br/>

    <a href="https://twitter.com/YOUR_TWITTER" target="_blank" style="text-decoration:none;">
      <img src="https://img.icons8.com/ios-filled/26/4a90e2/twitter.png" style="vertical-align:middle;"/> 
      &nbsp;Twitter
    </a>
    <br/>

    <a href="https://www.linkedin.com/in/rx98" target="_blank" style="text-decoration:none;">
      <img src="https://img.icons8.com/ios-filled/26/0A66C2/linkedin.png" style="vertical-align:middle;"/> 
      &nbsp;LinkedIn
    </a>

  </p>

theme: jekyll-theme-minimal
